"""create model tables

Revision ID: 4b8a9bd471bd
Revises: 
Create Date: 2022-09-28 12:53:54.185824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8a9bd471bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('number', sa.Numeric(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_account_id'), 'countries', ['account_id'], unique=False)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_index(op.f('ix_countries_zipcode'), 'countries', ['zipcode'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_account_id'), 'courses', ['account_id'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=True)
    op.create_table('degrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_degrees_account_id'), 'degrees', ['account_id'], unique=False)
    op.create_index(op.f('ix_degrees_id'), 'degrees', ['id'], unique=False)
    op.create_index(op.f('ix_degrees_name'), 'degrees', ['name'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('estimated_budget', sa.Float(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_account_id'), 'jobs', ['account_id'], unique=False)
    op.create_index(op.f('ix_jobs_description'), 'jobs', ['description'], unique=False)
    op.create_index(op.f('ix_jobs_estimated_budget'), 'jobs', ['estimated_budget'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_name'), 'jobs', ['name'], unique=False)
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualifications_account_id'), 'qualifications', ['account_id'], unique=False)
    op.create_index(op.f('ix_qualifications_certificate'), 'qualifications', ['certificate'], unique=False)
    op.create_index(op.f('ix_qualifications_id'), 'qualifications', ['id'], unique=False)
    op.create_index(op.f('ix_qualifications_organization'), 'qualifications', ['organization'], unique=False)
    op.create_index(op.f('ix_qualifications_start_year'), 'qualifications', ['start_year'], unique=False)
    op.create_index(op.f('ix_qualifications_summary'), 'qualifications', ['summary'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_account_id'), 'skills', ['account_id'], unique=False)
    op.create_index(op.f('ix_skills_description'), 'skills', ['description'], unique=False)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=False),
    sa.Column('degree_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['degree_id'], ['degrees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educations_account_id'), 'educations', ['account_id'], unique=False)
    op.create_index(op.f('ix_educations_country_id'), 'educations', ['country_id'], unique=False)
    op.create_index(op.f('ix_educations_course_id'), 'educations', ['course_id'], unique=False)
    op.create_index(op.f('ix_educations_degree_id'), 'educations', ['degree_id'], unique=False)
    op.create_index(op.f('ix_educations_end_year'), 'educations', ['end_year'], unique=False)
    op.create_index(op.f('ix_educations_id'), 'educations', ['id'], unique=False)
    op.create_index(op.f('ix_educations_school_name'), 'educations', ['school_name'], unique=False)
    op.create_index(op.f('ix_educations_start_year'), 'educations', ['start_year'], unique=False)
    op.create_table('jobskills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobskills_id'), 'jobskills', ['id'], unique=False)
    op.create_index(op.f('ix_jobskills_job_id'), 'jobskills', ['job_id'], unique=False)
    op.create_index(op.f('ix_jobskills_skill_id'), 'jobskills', ['skill_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('town', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('short_info', sa.String(), nullable=True),
    sa.Column('short_note', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_account_id'), 'profiles', ['account_id'], unique=False)
    op.create_index(op.f('ix_profiles_city'), 'profiles', ['city'], unique=False)
    op.create_index(op.f('ix_profiles_country_id'), 'profiles', ['country_id'], unique=False)
    op.create_index(op.f('ix_profiles_dob'), 'profiles', ['dob'], unique=False)
    op.create_index(op.f('ix_profiles_firstname'), 'profiles', ['firstname'], unique=False)
    op.create_index(op.f('ix_profiles_gender'), 'profiles', ['gender'], unique=False)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_lastname'), 'profiles', ['lastname'], unique=False)
    op.create_index(op.f('ix_profiles_region'), 'profiles', ['region'], unique=False)
    op.create_index(op.f('ix_profiles_short_info'), 'profiles', ['short_info'], unique=False)
    op.create_index(op.f('ix_profiles_short_note'), 'profiles', ['short_note'], unique=False)
    op.create_index(op.f('ix_profiles_street'), 'profiles', ['street'], unique=False)
    op.create_index(op.f('ix_profiles_town'), 'profiles', ['town'], unique=False)
    op.create_table('profileskills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profileskills_account_id'), 'profileskills', ['account_id'], unique=False)
    op.create_index(op.f('ix_profileskills_id'), 'profileskills', ['id'], unique=False)
    op.create_index(op.f('ix_profileskills_skill_id'), 'profileskills', ['skill_id'], unique=False)
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_account_id'), 'universities', ['account_id'], unique=False)
    op.create_index(op.f('ix_universities_country_id'), 'universities', ['country_id'], unique=False)
    op.create_index(op.f('ix_universities_id'), 'universities', ['id'], unique=False)
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_index(op.f('ix_universities_id'), table_name='universities')
    op.drop_index(op.f('ix_universities_country_id'), table_name='universities')
    op.drop_index(op.f('ix_universities_account_id'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_profileskills_skill_id'), table_name='profileskills')
    op.drop_index(op.f('ix_profileskills_id'), table_name='profileskills')
    op.drop_index(op.f('ix_profileskills_account_id'), table_name='profileskills')
    op.drop_table('profileskills')
    op.drop_index(op.f('ix_profiles_town'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_street'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_short_note'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_short_info'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_region'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_lastname'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_gender'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_firstname'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_dob'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_country_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_city'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_account_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_jobskills_skill_id'), table_name='jobskills')
    op.drop_index(op.f('ix_jobskills_job_id'), table_name='jobskills')
    op.drop_index(op.f('ix_jobskills_id'), table_name='jobskills')
    op.drop_table('jobskills')
    op.drop_index(op.f('ix_educations_start_year'), table_name='educations')
    op.drop_index(op.f('ix_educations_school_name'), table_name='educations')
    op.drop_index(op.f('ix_educations_id'), table_name='educations')
    op.drop_index(op.f('ix_educations_end_year'), table_name='educations')
    op.drop_index(op.f('ix_educations_degree_id'), table_name='educations')
    op.drop_index(op.f('ix_educations_course_id'), table_name='educations')
    op.drop_index(op.f('ix_educations_country_id'), table_name='educations')
    op.drop_index(op.f('ix_educations_account_id'), table_name='educations')
    op.drop_table('educations')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_description'), table_name='skills')
    op.drop_index(op.f('ix_skills_account_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_qualifications_summary'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_start_year'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_organization'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_id'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_certificate'), table_name='qualifications')
    op.drop_index(op.f('ix_qualifications_account_id'), table_name='qualifications')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_jobs_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_estimated_budget'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_description'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_account_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_degrees_name'), table_name='degrees')
    op.drop_index(op.f('ix_degrees_id'), table_name='degrees')
    op.drop_index(op.f('ix_degrees_account_id'), table_name='degrees')
    op.drop_table('degrees')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_account_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_countries_zipcode'), table_name='countries')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_account_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
