"""add ondelete to all fkeys

Revision ID: 6e5b2f47b73a
Revises: 4b8a9bd471bd
Create Date: 2022-09-28 13:05:45.493683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5b2f47b73a'
down_revision = '4b8a9bd471bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('countries_account_id_fkey', 'countries', type_='foreignkey')
    op.create_foreign_key(None, 'countries', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('courses_account_id_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('degrees_account_id_fkey', 'degrees', type_='foreignkey')
    op.create_foreign_key(None, 'degrees', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('educations_course_id_fkey', 'educations', type_='foreignkey')
    op.drop_constraint('educations_account_id_fkey', 'educations', type_='foreignkey')
    op.drop_constraint('educations_country_id_fkey', 'educations', type_='foreignkey')
    op.drop_constraint('educations_degree_id_fkey', 'educations', type_='foreignkey')
    op.create_foreign_key(None, 'educations', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'educations', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'educations', 'countries', ['country_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'educations', 'degrees', ['degree_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('jobs_account_id_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('jobskills_skill_id_fkey', 'jobskills', type_='foreignkey')
    op.drop_constraint('jobskills_job_id_fkey', 'jobskills', type_='foreignkey')
    op.create_foreign_key(None, 'jobskills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'jobskills', 'accounts', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profiles_country_id_fkey', 'profiles', type_='foreignkey')
    op.drop_constraint('profiles_account_id_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'countries', ['country_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profiles', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profileskills_skill_id_fkey', 'profileskills', type_='foreignkey')
    op.drop_constraint('profileskills_account_id_fkey', 'profileskills', type_='foreignkey')
    op.create_foreign_key(None, 'profileskills', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profileskills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('qualifications_account_id_fkey', 'qualifications', type_='foreignkey')
    op.create_foreign_key(None, 'qualifications', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('skills_account_id_fkey', 'skills', type_='foreignkey')
    op.create_foreign_key(None, 'skills', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('universities_country_id_fkey', 'universities', type_='foreignkey')
    op.drop_constraint('universities_account_id_fkey', 'universities', type_='foreignkey')
    op.create_foreign_key(None, 'universities', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'universities', 'countries', ['country_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'universities', type_='foreignkey')
    op.drop_constraint(None, 'universities', type_='foreignkey')
    op.create_foreign_key('universities_account_id_fkey', 'universities', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('universities_country_id_fkey', 'universities', 'countries', ['country_id'], ['id'])
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.create_foreign_key('skills_account_id_fkey', 'skills', 'accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'qualifications', type_='foreignkey')
    op.create_foreign_key('qualifications_account_id_fkey', 'qualifications', 'accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'profileskills', type_='foreignkey')
    op.drop_constraint(None, 'profileskills', type_='foreignkey')
    op.create_foreign_key('profileskills_account_id_fkey', 'profileskills', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('profileskills_skill_id_fkey', 'profileskills', 'skills', ['skill_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_account_id_fkey', 'profiles', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('profiles_country_id_fkey', 'profiles', 'countries', ['country_id'], ['id'])
    op.drop_constraint(None, 'jobskills', type_='foreignkey')
    op.drop_constraint(None, 'jobskills', type_='foreignkey')
    op.create_foreign_key('jobskills_job_id_fkey', 'jobskills', 'accounts', ['job_id'], ['id'])
    op.create_foreign_key('jobskills_skill_id_fkey', 'jobskills', 'skills', ['skill_id'], ['id'])
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_account_id_fkey', 'jobs', 'accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.create_foreign_key('educations_degree_id_fkey', 'educations', 'degrees', ['degree_id'], ['id'])
    op.create_foreign_key('educations_country_id_fkey', 'educations', 'countries', ['country_id'], ['id'])
    op.create_foreign_key('educations_account_id_fkey', 'educations', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('educations_course_id_fkey', 'educations', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'degrees', type_='foreignkey')
    op.create_foreign_key('degrees_account_id_fkey', 'degrees', 'accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_account_id_fkey', 'courses', 'accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'countries', type_='foreignkey')
    op.create_foreign_key('countries_account_id_fkey', 'countries', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###
